services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: StoryStack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=StoryStack
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  postgres_data:
