services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: StoryStack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
