services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: StoryStack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
